### ISSUE TITLE
division by zero error in write_qv_stats

### ISSUE THREAD

**Issue by tbenavi1** [nhansen/q100bench#1]
Hello,

I ran q100bench on my data, and I received the following error:

```
Traceback (most recent call last):
  File "/tgen_labs/barthel/software/github/external/q100bench/venv/bin/q100bench", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tgen_labs/barthel/software/github/external/q100bench/q100bench/bench.py", line 201, in main
    stats.write_qv_stats(benchmark_stats, outputfiles, args)
  File "/tgen_labs/barthel/software/github/external/q100bench/q100bench/stats.py", line 476, in write_qv_stats
    snverrorspermb = int(totaltypesnverrors/totalassemblybasesinaligns*1000000)
                         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

Any ideas how to fix it? Thank you.

**Comment by nhansen** [comment]
Thanks for reporting this. This error should only happen if there are no alignments in the bam file you passed to the program. Can you share more about how you aligned your assembly? Which benchmark you're comparing to (v1.0.1, v1.1?)

**Comment by tbenavi1** [comment]
I used minimap2 to align the assembly, and I am comparing to v1.1. I realized that I was using a sam file as input, but the tool requires an indexed bam file. Thank you.

**Comment by nhansen** [comment]
Thanks Tim! I'll consider adding support for uncompressed alignments in the future
