### ISSUE TITLE
No results for phasing statistics and mononucleotide run accuracy

### ISSUE THREAD

**Issue by tbenavi1** [nhansen/q100bench#2]
Hello,

I ran q100bench on my assembly and for the phasing statistics section I got:
```
Phasing statistics (0 benchmark heterozygous sites with an aligned maternal or paternal assembly allele):

Number of maternal alleles within alignments: 0
Number of paternal alleles within alignments: 0
Number of switches between maternal and paternal alleles within a contig alignment: 0
Switch rate per base within aligned sequence: 0.0 per Mb
```

Also, for the mononucleotide run accuracy section I got:
```
Mononucleotide run accuracy:

Total number of true assembly mononucleotide runs of ten or more bases covered by NHA_p1_hifiasm_hap1 alignments: 0
Number of mononucleotide runs correct in assembly: 0 (NA%)
Number of mononucleotide runs with assembly alleles matching the alternate haplotype: 0 (NA%)
Number of mononucleotide runs with non-alternate alleles of fewer or more of the same base in the assembly: 0 (NA%)
Number of mononucleotide runs with erroneous alleles other than extensions or contractions: 0 (NA%)
```

Is this to be expected? Is there some way I can get nonzero results? Thanks for the information.

**Comment by nhansen** [comment]
Hi Timothy! Can you post the commands you used to create your BAM file, as well as to run q100bench? There might also be useful information in the log file produced by the program

**Comment by tbenavi1** [comment]
To create the bam, I used:
```
minimap2 -ax asm5 hg002v1.1.fasta.gz assembly.haplotype1.fasta > output.sam
```

To run q100bench:
```
q100bench -b output.sorted.bam -r hg002v1.1.fasta.gz -q assembly.haplotype1.fasta -p assembly/q100bench/verkko/hap1 -A verkko_hap1 -B q100bench
```

Part of the log file:
```
Error: Unable to open file /data/Phillippy/projects/HG002_diploid/benchmarking/resources/v1.1/v1.1.mnr10.bed. Exiting.
Error in library(karyoploteR) : there is no package called ‘karyoploteR’
Execution halted
Error in library(karyoploteR) : there is no package called ‘karyoploteR’
Execution halted
null device
          1
Error in read.table(mononucsitefile, header = FALSE, sep = "\t") :
  no lines available in input
Execution halted
pdf
  2
```
Ah, so it looks like there might be a hard coded file path for the v1.1.mnr10.bed file. And also, there is a missing ‘karyoploteR’ dependency.

**Comment by nhansen** [comment]
Thanks for reporting this. It sounds as if I should have the program fail if it doesn't find the appropriate config files. You'll need to download the resource tarball and edit your config file to specify file locations as described in the "Dependencies" section of this repo's README. I'll expand the README to give more details about setting up the config file, and mention the dependency on karyoploteR, which is part of BioConductor.

**Comment by tbenavi1** [comment]
Thank you.
